-- MySQL Script generated by MySQL Workbench
-- qua 27 fev 2019 11:20:06 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema combustivel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `combustivel` ;

-- -----------------------------------------------------
-- Schema combustivel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `combustivel` DEFAULT CHARACTER SET utf8 ;
USE `combustivel` ;

-- -----------------------------------------------------
-- Table `combustivel`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `combustivel`.`estado` ;

CREATE TABLE IF NOT EXISTS `combustivel`.`estado` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(75) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `uf` VARCHAR(5) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `combustivel`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `combustivel`.`cidade` ;

CREATE TABLE IF NOT EXISTS `combustivel`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `estado` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Cidade_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `combustivel`.`estado` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5565
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Cidade_estado` ON `combustivel`.`cidade` (`estado` ASC);


-- -----------------------------------------------------
-- Table `combustivel`.`posto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `combustivel`.`posto` ;

CREATE TABLE IF NOT EXISTS `combustivel`.`posto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `cnpj` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `municipio` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `bandeira` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `distribuidora` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `origem` VARCHAR(25) COLLATE 'utf32_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `combustivel`.`pesquisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `combustivel`.`pesquisa` ;

CREATE TABLE IF NOT EXISTS `combustivel`.`pesquisa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_posto` INT(11) NULL DEFAULT NULL,
  `metodo_coleta` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `numero_nota_fiscal` INT(22) NOT NULL,
  `produto` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `data_de_compra` TIMESTAMP NULL DEFAULT NULL,
  `preco_de_compra` DECIMAL(7,4) NOT NULL,
  `data_da_venda_coleta` TIMESTAMP NULL DEFAULT NULL,
  `preco_de_venda` DECIMAL(7,4) NOT NULL,
  `margem_reais` DECIMAL(7,4) NULL DEFAULT NULL,
  `variacao` DECIMAL(3,2) NULL DEFAULT NULL,
  `f_de_abastecimento` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `media_mensal_litro` DECIMAL(7,3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_posto_pesquisa`
    FOREIGN KEY (`id_posto`)
    REFERENCES `combustivel`.`posto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_posto_pesquisa` ON `combustivel`.`pesquisa` (`id_posto` ASC);


-- -----------------------------------------------------
-- Table `combustivel`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `combustivel`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `combustivel`.`usuarios` (
  `nome` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `sobrenome` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `pais` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `estado` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `cidade` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `senha` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
